# PnP loose mode required for wrangler CLI
pnpMode: loose

# Required for stylelint
packageExtensions:
  "stylelint@*":
    dependencies:
      "supports-color": "^5.3.0"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
