compressionLevel: mixed
enableGlobalCache: false

packageExtensions:
  debug@*:
    dependencies:
      supports-color: ^5.3.0
  stylelint@*:
    dependencies:
      supports-color: ^5.3.0

yarnPath: .yarn/releases/yarn-4.9.1.cjs
