packageExtensions:
  debug@*:
    dependencies:
      supports-color: ^5.3.0
  stylelint@*:
    dependencies:
      supports-color: ^5.3.0

# Required for Wrangler CLI
pnpMode: loose

yarnPath: .yarn/releases/yarn-3.5.1.cjs
